---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc"
    mode: "0644"

- name: "Bash | Copy .profile"
  ansible.builtin.copy:
    src: ".profile"
    dest: "{{ ansible_facts['user_dir'] }}/.profile"
    mode: "0644"

- name: "Bash | Copy custom bash config"
  ansible.builtin.copy:
    dest: "{{ ansible_facts['user_dir'] }}/.config/"
    src: "bash"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Bash | {{ ansible_facts['distribution'] }} | Identify distribution config"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/os/{{ ansible_facts['distribution'] }}"
  register: bash_os_distribution_config

- name: "Bash | {{ ansible_facts['os_family'] }} | Identify os family config"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/os/{{ ansible_facts['os_family'] }}"
  register: bash_os_family_config
  when: not bash_os_distribution_config.stat.exists

- name: "Bash | Calculate os config src"
  ansible.builtin.set_fact:
    bash_os_config: "{{ bash_os_distribution_config if bash_os_distribution_config.stat.exists else bash_os_family_config }}"

- name: "Bash | Copy custom bash config for os: {{ bash_os_config.stat.path | basename }}"
  ansible.builtin.copy:
    dest: "{{ ansible_facts['user_dir'] }}/.config/bash/"
    src: "{{ bash_os_config.stat.path }}/"
    mode: "0644"
    force: true
  when:
    - bash_os_config is defined
    - bash_os_config.stat.exists
