---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Set config source"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/override_utils/tasks/set_config_source.yml"
  vars:
    config_name: taskfile

- name: TASKFILE | Update Bash Completions
  block:
    - name: TASKFILE | Ensure .task config dir exists
      ansible.builtin.file:
        name: "{{ ansible_facts['env']['HOME'] }}/.task"
        state: directory
        mode: "0755"

    - name: TASKFILE | Ensure .task/completions dir exists
      ansible.builtin.file:
        name: "{{ ansible_facts['env']['HOME'] }}/.task/completions"
        state: directory
        mode: "0755"

    - name: TASKFILE | Pull latest task bash completion
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/go-task/task/main/completion/bash/task.bash"
        dest: "{{ ansible_facts['env']['HOME'] }}/.task/completions/task.bash"
        mode: "0644"

- name: TASKFILE | Load OS-Specific Taskfile
  block:
    - name: "TASKFILE | {{ ansible_facts['distribution'] }} | Identify distribution config"
      ansible.builtin.stat:
        path: "{{ _files_path }}/os/Taskfile_{{ ansible_facts['distribution'] }}.yml"
      register: taskfile_os_distribution_config

    - name: "TASKFILE | {{ ansible_facts['os_family'] }} | Identify os family config"
      ansible.builtin.stat:
        path: "{{ _files_path }}/os/Taskfile_{{ ansible_facts['os_family'] }}.yml"
      register: taskfile_os_family_config
      when: not taskfile_os_distribution_config.stat.exists

    - name: "TASKFILE | Calculate os config src"
      ansible.builtin.set_fact:
        taskfile_os_config: "{{ taskfile_os_distribution_config if taskfile_os_distribution_config.stat.exists else taskfile_os_family_config }}"

    - name: "TASKFILE | Copy custom bash config for os: {{ taskfile_os_config.stat.path | basename }}"
      ansible.builtin.copy:
        dest: "{{ ansible_facts['user_dir'] }}/Taskfile.yml"
        src: "{{ taskfile_os_config.stat.path }}"
        mode: "0644"
        force: true
      when:
        - taskfile_os_config is defined
        - taskfile_os_config.stat.exists

    - name: "TASKFILE | Mark Ansible-managed file."
      ansible.builtin.blockinfile:
        dest: "{{ ansible_facts['user_dir'] }}/Taskfile.yml"
        mode: "0644"
        insertbefore: 'version:'
        append_newline: true
        block: |
          # Ansible Managed File
          # Original file: {{ taskfile_os_config.stat.path | basename }}
      when:
        - taskfile_os_config is defined
        - taskfile_os_config.stat.exists
