# Yazi configuration
# https://yazi-rs.github.io/docs/configuration/yazi

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 1000
max_height = 1000
image_quality = 75

[opener]
edit = [
  { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" },
]

[open]
rules = [
  { name = "*/", use = ["edit", "open", "reveal"] },
  { mime = "text/*", use = ["edit", "reveal"] },
  { mime = "image/*", use = ["open", "reveal"] },
  { mime = "video/*", use = ["open", "reveal"] },
  { mime = "audio/*", use = ["open", "reveal"] },
  { mime = "inode/x-empty", use = ["edit", "reveal"] },
  { mime = "application/json", use = ["edit", "reveal"] },
  { mime = "*/javascript", use = ["edit", "reveal"] },
  { name = "*", use = ["open", "reveal"] },
]
