---
- name: "Atuin | MacOSX | Install"
  community.general.homebrew:
    name: atuin
    state: present

- name: "Atuin | MacOSX | Deploy Config"
  block:
    - name: "Ensure atuin .config dir exists"
      ansible.builtin.file:
        name: atuin
        state: directory
        mode: "0755"

    - name: "Deploy Config"
      ansible.builtin.copy:
        src: config.toml
        dest: "{{ ansible_user_dir }}/.config/atuin/config.toml"
        mode: "0644"
