---
- name: K8s | Adding kubernetes apt key
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s.repo_version }}/deb/Release.key"
    state: present
    keyring: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
  become: true

- name: K8s | Adding kubernetes apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s.repo_version }}/deb/ /"
    filename: pkgs.k8s.io_core_stable_deb
  become: true

- name: K8s | Installing Kubernetes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    force: true
  loop:
    - kubectl
  become: true

# - name: K8s | Configure .kube/config
#   block:
#     - name: K8s | Ensure .kube directory exists
#       ansible.builtin.file:
#         path: "~/.kube"
#         state: directory
#         mode: "0755"
#
#     - name: K8s | Copy .kube/config file
#       ansible.builtin.copy:
#         src: config
#         dest: "~/.kube/config"
#         mode: "0600"
