---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Ensure config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/yazi"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Symlink yazi.toml"
  ansible.builtin.file:
    src: "{{ role_path }}/files/yazi.toml"
    dest: "{{ ansible_facts['user_dir'] }}/.config/yazi/yazi.toml"
    state: link
    force: true

- name: "{{ role_name }} | Symlink keymap.toml"
  ansible.builtin.file:
    src: "{{ role_path }}/files/keymap.toml"
    dest: "{{ ansible_facts['user_dir'] }}/.config/yazi/keymap.toml"
    state: link
    force: true

- name: "{{ role_name }} | Symlink theme.toml"
  ansible.builtin.file:
    src: "{{ role_path }}/files/theme.toml"
    dest: "{{ ansible_facts['user_dir'] }}/.config/yazi/theme.toml"
    state: link
    force: true
