---
- name: Remove oh-my-bash Install Script
  ansible.builtin.file:
    path: /tmp/oh-my-bash.install.sh
    state: absent

- name: Bash | Cleanup oh-my-bash install script
  ansible.builtin.file:
    path: /{{ ansible_user_dir }}/oh-my-bash.install.sh
    state: absent
