---
- name: "Zoxide | {{ ansible_facts['distribution'] }} | Install Zoxide"
  ansible.builtin.apt:
    name:
      - zoxide
    state: present
  become: true
  when: ansible_facts['distribution_version'] >= '21.04'
