---
- name: Nomad | {{ ansible_distribution }} | Add the HashiCorp GPG key.
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    state: present
  become: true

- name: Nomad | {{ ansible_distribution }} | Add the official HashiCorp Linux repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  become: true

- name: Nomad | {{ ansible_distribution }} | Install Nomad
  ansible.builtin.apt:
    name: nomad
    state: present
    update_cache: yes
  become: true
