---
- name: "Terraform | MacOSX | Install Terraform"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - terraform
    - terraform-ls
    - tfsec
    - terraform-docs
    - terragrunt
