---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Create Ghostty config directory"
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/ghostty"
    state: directory
    mode: '0755'

- name: "{{ role_name }} | Deploy Configuration"
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/ghostty/config"
    mode: "0644"

- name: "{{ role_name }} | Deploy Shaders directory"
  ansible.builtin.copy:
    src: shaders
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/ghostty/"
    mode: "0644"
    directory_mode: "0755"

- name: "{{ role_name }} | Deploy Themes directory"
  ansible.builtin.copy:
    src: themes
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/ghostty/"
    mode: "0644"
    directory_mode: "0755"
