---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Ensure Powershell profile directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/powershell"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Deploy Powershell profile"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/powershell/profile.ps1"
    src: "profile.ps1"
    mode: "0644"
