---
- name: "Hammerspoon | MacOSX | Cleanup latest GridLayout.spoon zip"
  ansible.builtin.file:
    name: "{{ ansible_facts['user_dir'] }}/.hammerspoon/Spoons/GridLayout.spoon.zip"
    state: absent
