---
- name: Cleanup fzf downloaded tar
  ansible.builtin.file:
    path: "/tmp/{{ fzf_file }}.tar.gz"
    state: absent
  become: true

- name: Remove extracted fzf directory
  ansible.builtin.file:
    path: /tmp/fzf
    state: absent
  become: true
