---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Arch Tasks
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
