---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: "LSD | Ensure ~/.config/lsd exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/lsd"
    state: directory
    mode: "0755"

- name: "LSD | Copy lsd config"
  ansible.builtin.copy:
    src: "config.yaml"
    dest: "{{ ansible_facts['user_dir'] }}/.config/lsd/config.yaml"
    mode: "0644"

- name: "LSD | Copy colors.yaml"
  ansible.builtin.copy:
    src: "colors.yaml"
    dest: "{{ ansible_facts['user_dir'] }}/.config/lsd/colors.yaml"
    mode: "0644"
