---
- name: "Docker | MacOSX | Install Docker"
  community.general.homebrew:
    name: docker
    state: present

# IF THIS IS NEEDED AS-IS, MOVE IT TO main.yml
# - name: "Docker | Enable service"
#   ansible.builtin.systemd:
#     enabled: true
#     name: docker
#     state: started
#   become: true
#   when: not ansible_host_environment_is_wsl
#
# - name: "Docker | Add to group"
#   ansible.builtin.user:
#     append: true
#     groups: docker
#     name: "{{ ansible_facts['env']['USER'] }}"
#   become: true
#
# - name: "Docker | Ensure docker data directory exists"
#   ansible.builtin.file:
#     path: "{{  ansible_facts['user_dir'] }}/.local/lib/docker"
#     state: directory
#     mode: "0710"
#   become: true
#
# - name: "Docker | Copy daemon.json"
#   ansible.builtin.template:
#     dest: "/etc/docker/daemon.json"
#     src: "daemon.json"
#     mode: "0644"
#   become: true
#   notify: restart_docker
