---
# General
# If is ~, the latest stable version will be used
gh_user: sharkdp
gh_repo: bat
gh_repo_url: "https://github.com/{{ gh_user }}/{{ gh_repo }}"
target_bat_version: ''

# DEBIAN
debian_url: ~
