---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "BTOP | Ensure btop directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/btop
    - ~/.config/btop/themes

- name: "BTOP | Copy btop config"
  ansible.builtin.copy:
    src: btop.conf
    dest: ~/.config/btop/btop.conf
    mode: "0644"

- name: "BTOP | Copy btop colors"
  ansible.builtin.copy:
    src: catppuccin_mocha.theme
    dest: ~/.config/btop/themes/catppuccin_mocha.theme
    mode: "0644"
