---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Set config source"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/override_utils/tasks/set_config_source.yml"
  vars:
    config_name: btop

- name: "BTOP | Ensure btop directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/btop
    - ~/.config/btop/themes

- name: "BTOP | Copy btop config"
  ansible.builtin.copy:
    src: "{{ _files_path }}/btop.conf"
    dest: ~/.config/btop/btop.conf
    mode: "0644"

- name: "BTOP | Copy btop colors"
  ansible.builtin.copy:
    src: "{{ _files_path }}/catppuccin_mocha.theme"
    dest: ~/.config/btop/themes/catppuccin_mocha.theme
    mode: "0644"
