---
- name: "Zellij | Download Latest Version JSON"
  ansible.builtin.uri:
    url: https://api.github.com/repos/zellij-org/zellij/releases/latest
  register: zellij_latest_version_json
  changed_when: false

- name: "Zellij | Registering zellij Latest Release"
  ansible.builtin.set_fact:
    zellij_latest_release: "{{ zellij_latest_version_json.json.tag_name }}"

- name: "Zellij | Registering zellij Latest Version"
  ansible.builtin.set_fact:
    zellij_latest_version: "{{ zellij_latest_release.stdout|default('') }}"

- name: "Zellij | Getting version information"
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/zellij --version | cut -d ' ' -f 2
  register: current_zellij_version
  changed_when: false
  failed_when: false

- name: "Zellij | Registering zellij Current Version"
  ansible.builtin.set_fact:
    zellij_current_version: "v{{ current_zellij_version.stdout }}"

- name: "Zellij | Show current_zellij_version debug"
  ansible.builtin.debug:
    var: zellij_current_version

- name: "Zellij | Show zellij_latest_release debug"
  ansible.builtin.debug:
    var: zellij_latest_release

- name: "Zellij | Install"
  when: zellij_latest_release not in zellij_current_version|default('')
  block:
    - name: "Zellij | Define zellij_file"
      ansible.builtin.set_fact:
        zellij_file: "zellij-{{ ansible_machine }}-unknown-linux-musl"

    - name: "Zellij | Ensure clean download destination"
      ansible.builtin.file:
        path: "/tmp/{{ zellij_file }}.tar.gz"
        state: absent
      become: true

    - name: "Zellij | Downloading zellij Release"
      ansible.builtin.get_url:
        url: "https://github.com/zellij-org/zellij/releases/download/{{ zellij_latest_release }}/{{ zellij_file }}.tar.gz"
        dest: /tmp/
        mode: u=rwx,g=rx,o=rx
        force: true
      notify:
        - Cleanup zellij downloaded tar

    - name: "Zellij | Ensure clean extraction destination"
      ansible.builtin.file:
        path: "/tmp/zellij"
        state: absent
      become: true

    - name: "Zellij | Extract zellij tar file"
      ansible.builtin.unarchive:
        src: "/tmp/{{ zellij_file }}.tar.gz"
        dest: /tmp

    - name: "Zellij | Remove any current zellij installations"
      ansible.builtin.file:
        path: /usr/local/bin/zellij
        state: absent
      become: true

    - name: "Zellij | Install zellij"
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/zellij
        dest: /usr/local/bin/
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        force: true
        mode: u=rwx,g=rx,o=rx
      become: true
      notify:
        - Remove extracted zellij directory

- name: "Zellij | Ensure zellij config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/zellij"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: "Zellij | Copy config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/zellij/config.yml"
    src: "config.kdl"
    mode: u=rwx,g=rx,o=rx
